### ISSUE TITLE
Explicit license for csvy format and website content

### ISSUE THREAD

**Issue by CharlesNepote** [csvy/csvy.github.io#10]
We need to know the legal conditions behind csvy usage and the website contents.

I would find Creative Commons BY 4.0 interesting.

**Comment by jcolomb** [comment]
I would even go for CC0 if posiible. But we would first need more content (?).

**Comment by CharlesNepote** [comment]
CC0 is also fine for me. Licencing is a first step, content can be the next one.

**Comment by jrovegno** [comment]
@CharlesNepote Can you make a pull request for this?

**Comment by CharlesNepote** [comment]
Done. See #16
