### ISSUE TITLE
JSON Table Schema renamed to Table Schema

### ISSUE THREAD

**Issue by danfowler** [csvy/csvy.github.io#11]
https://github.com/frictionlessdata/specs/issues/334

http://specs.frictionlessdata.io/table-schema/

**Comment by jrovegno** [comment]
@danfowler thank for the hint.

**Comment by danfowler** [comment]
@jrovegno it has also been updated, and a blog post summarizing changes is coming soon.

**Comment by jrovegno** [comment]
@danfowler What do think about this PR #12 ?

**Comment by jrovegno** [comment]
Closed by #12
