### ISSUE TITLE
a completely related strategy to make it human writable

### ISSUE THREAD

**Issue by jcolomb** [csvy/csvy.github.io#13]
Dear all,

I think finding a way to pool metadata and data into one file is great and the way to go. I love the idea of csvy. Thing is, if the metadata needs a different program to be written, it will done only by techies.

When I saw the new read_csv function from readr, I got an idea... My proposition would be the following, take everything that is good in YAML, but transform its format to be csv. This would be the example:
```
---,---
name, my-dataset
description, "this is an example of the new csv format, including metadata on top."
author, "Julien Colomb"

fields, name, title, type,desciption, constraints
fields,var1,variable 1, string, explaining var1, required
fields, var2, variable 2, integer
fields, var3, variable 3, number

---,---
var1,var2,var3
A,1,2.5
B,3,4.3
```
why I think it could be cool:
+ scanning for the first 8 character, if the first 3 are "-" at the beginning, the fourth one is the delimiter, the 8th is the line break. This would make csv file readable, whatever the the delimiter is, and makes compatibility issues (with excel) obsolete. In addition if the first 3 character are not "-", there is no metadata and the program can (try to) read the file as a normal csv.

+ You can read and write the metadata in your normal spreadsheet program.

+ if templates is made for fields names, it is easy **for any user** to enter metadata, you just copy and paste-transposed the headers and fill the table.
 
What do you think?

This  issue is licenced CC0.

**Comment by jrovegno** [comment]
Could be nice, but it steers away from one of the main benefits of csvy, which is to combine existing standards, in a simple way, to reuse the YAML and CSV libraries present in most languages. We are at the limit of reinventing the wheel, transforming the schema table from JSON to CSV could be passing that limit.
Regards

**Comment by pwalsh** [comment]
Check out http://metatab.org which serialises Tabular Data Package as a sheet in a spreadsheet. If the goal is human edit ability, I think it is a more intuitive approach than combining multiple data structures in a single file.

**Comment by jrovegno** [comment]
@jcolomb I think that @pwalsh give us a good alternative for csvy for this case.
I'm going to close this issue, because this suggestions change the root of the cvsy file. If you have any thoughts, we are open to hear about that.
