### ISSUE TITLE
(New) Ruby CsvReader Library / Gem Supports CSV with meta data block (front matter) in YAML (CSVY) "out-of-the-box" 

### ISSUE THREAD

**Issue by geraldb** [csvy/csvy.github.io#23]
Hello,
 In the latest update v1.1 of the ruby csvreader library / gem - see <https://github.com/csvreader/csvreader> -  I've added support for CSV with meta data block (front matter) in YAML (CSVY) "out-of-the-box". Yes, it's turned on by default in the CSV v1.0 "The Right Way" format / flavor. See <https://github.com/csvreader/csvreader/blob/master/test/test_parser_meta.rb> for (test) examples.   Keep up the great work with CSVY. Cheers. Prost. 

PS: Here's the code snippet:

``` ruby
def test_parse
  records = [["a", "b", "c"],
             ["1", "2", "3"]]

  assert_equal records, parser.parse( <<TXT )
# with meta data
## see https://blog.datacite.org/using-yaml-frontmatter-with-csv/
---
columns:
- title: Purchase Date
  type: date
- title: Item
  type: string
- title: Amount (€)
  type: float
---
a,b,c
1,2,3
TXT

  pp parser.meta
  meta = { "columns"=>
             [{"title"=>"Purchase Date", "type"=>"date"},
              {"title"=>"Item",          "type"=>"string"},
              {"title"=>"Amount (€)",    "type"=>"float"}]
         }
  assert_equal meta, parser.meta


  assert_equal records, parser.parse( <<TXT )
# with (empty) meta data
---
---
a,b,c
1,2,3
TXT

  pp parser.meta
  meta = {}
  assert_equal meta, parser.meta



  assert_equal records, parser.parse( <<TXT )
# without meta data
a,b,c
1,2,3
TXT

  assert_nil parser.meta
end
```

**Comment by jrovegno** [comment]
Very interesting initiative, I added on csvy.org a link to "csvreader" for ruby users who want to read the cvsy metadata easily.
