### ISSUE TITLE
Standard in the metadata format

### ISSUE THREAD

**Issue by jcolomb** [csvy/csvy.github.io#3]
I am quite excited: metadata one can actually read: sounds cool.

However, how could we/you bring some standars in the metadata format itself? In the example, the date format is not given, shouldn't we try to make some organisation. Maybe with a versioning of the metadata format itself? Going semantic from the start?

sorry if the question is stupid, I am no specialist...

**Comment by karthik** [comment]
All good questions, Julien. We'll work through these shortly.

**Comment by jcolomb** [comment]
Nice to see you on that project Karthik!

**Comment by mfenner** [comment]
One of the things I like about YAML frontmatter is flexibility. The downside is of course that everyone will use it slightly differently. So some reasonable middle ground is probably good.

As for formatting dates, the JSON Table Schema spec has a `format` parameter:

```
fields:
  - name: publication_date
    type: date
    format: YYYY-MM-DD
```

**Comment by jrovegno** [comment]
As much as possible csvy will follow the [Table Schema defined by the OKFN](https://frictionlessdata.io/specs/table-schema/).
