### ISSUE TITLE
#csvy already taken: how to tweet this?

### ISSUE THREAD

**Issue by jcolomb** [csvy/csvy.github.io#6]
it is not as stupid as to call a r package "twitteR", but still annoying. Change the name, find a different hashtag which we will make official here, or get one million tweets #csvy, such that other users of the # will change theirs?

(ok now I go to bed...)

**Comment by karthik** [comment]
I don't think a hashtag conflict is a big driver as far as choosing a name for this effort.

**Comment by mfenner** [comment]
I was happy that `csvy.org` was available.

**Comment by jrovegno** [comment]
@jcolomb I do not think it's a problem unless spelling wrong #curvy #yoga becomes very popular.
